---
.release:
  stage: release
  image: docker:latest
  script:
    - chmod +x ./.gitlab/ci/scripts/02-00-release.sh
    - ./.gitlab/ci/scripts/02-00-release.sh

release:demo:
  extends: .release
  rules:
    - if: $CI_COMMIT_TAG
    - when: manual

.post-release:security:
  stage: release
  trigger:
    include:
      - project: 'security/AppSec'
        file:
          - 'container-scanning.yml'
          - 'dast.yml'
  variables:
    DAST_API_SCAN: "true"
    DAST_SWAGGER_FILE_ADDR: "${CI_SERVER_URL}/${CI_PROJECT_PATH}/-/blob/master/drivers/api/user/swagger.yml"

post-release:security:demo:
  extends: .post-release:security
  needs:
    - release:demo
  variables:
    CONTAINER_SCANNING_IMAGE_NAME: "${IMG}"
    CONTAINER_SCANNING_REGISTRY: "${IMG_REGISTRY}"
    CONTAINER_SCANNING_USERNAME: "${IMG_RW_USERNAME}"
    CONTAINER_SCANNING_PASSWORD: "${IMG_RW_PASSWORD}"
