---
deploy:argo:
  stage: prebuild
  image:
    name: "${ARGO_IMAGE}"
    entrypoint: ["/bin/sh", "-c"]
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - chmod +x ./.gitlab/ci/scripts/03-00-deploy-argo.sh
    - ./.gitlab/ci/scripts/03-00-deploy-argo.sh

.deploy:helm:
  stage: deploy
  image:
    name: "${HELM_IMAGE}"
    entrypoint: ["/bin/sh", "-c"]
  script:
    - apk add --update ncurses
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - chmod +x ./.gitlab/ci/scripts/03-01-deploy-helm.sh
    - ./.gitlab/ci/scripts/03-01-deploy-helm.sh
  variables:
    SECURE_FILES_DOWNLOAD_PATH: "./.deployment/lookhub/secrets/"

deploy:helm:demo:
  extends: .deploy:helm
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
  needs:
    - post-release:security:demo
  variables:
    ENVIRONMENT: "demo"
