---
.deploy:
  stage: deploy
  image:
    name: "${HELM_IMAGE}"
    entrypoint: ["/bin/sh", "-c"]
  script:
    - apk add --update ncurses
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - chmod +x ./.gitlab/ci/scripts/03-00-deploy.sh
    - ./.gitlab/ci/scripts/03-00-deploy.sh
  variables:
    SECURE_FILES_DOWNLOAD_PATH: "./.deployment/lookhub/secrets/"

deploy:demo:
  extends: .deploy
  needs:
    - post-release:security:demo
  variables:
    ENVIRONMENT: "demo"
    NAMESPACE: "${KUBE_NS}"
    KUBE_APISERVER: "${KUBE_ENDPOINT}"
    KUBE_TOKEN: "${KUBE_TOKEN}"
    IMG_REGISTRY: "${IMG_REGISTRY}"
    IMG_REPOSITORY: "${IMG_REPOSITORY}"
    IMG_TAG: "${IMG_TAG}"
