stages:
  - prebuild
  - build
  - release
  - deploy

variables:
  GO_IMAGE: "registry.snapp.tech/docker/golang:1.23-alpine"
  GO_PROXY: "https://repo.snapp.tech/repository/goproxy"
  HELM_IMAGE: "alpine/helm:latest"
  HELM_CHART_DIR: ".deployment/${CI_PROJECT_NAME}"

  IMG_REGISTRY: "${CI_REGISTRY}"
  IMG_REPOSITORY: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
  IMG_TAG: "${CI_COMMIT_REF_NAME}"
  IMG: "${IMG_REGISTRY}/${IMG_REPOSITORY}:${IMG_TAG}"
  IMG_RW_USERNAME: "${CI_REGISTRY_USER}"
  IMG_RW_PASSWORD: "${CI_REGISTRY_PASSWORD}"

  KUBE_NS: "${CI_PROJECT_NAMESPACE}"
  KUBE_ENDPOINT: "https://api.okd4.teh-1.snappcloud.io:6443"
  KUBE_TOKEN: "${KUBE_TOKEN_TEH1}"

include:
  - local: .gitlab/ci/templates/00-prebuild.gitlab-ci.yml
  - local: .gitlab/ci/templates/01-build.gitlab-ci.yml
  - local: .gitlab/ci/templates/02-release.gitlab-ci.yml
  - local: .gitlab/ci/templates/03-deploy.gitlab-ci.yml
