stages:
  - prebuild
  - build
  - release
  - deploy

variables:
  GO_IMAGE: "golang:1.23-alpine"
  GO_PROXY: "https://proxy.golang.org"
  HELM_IMAGE: "alpine/helm:latest"
  HELM_CHART_DIR: ".deployment/${CI_PROJECT_NAME}"
  ARGO_IMAGE: "argoproj/argocd:v2.6.15"

  IMG_REGISTRY:
    description: "Docker image registry to push the image into such as `ghcr.io`. Default = GitLab's container registry"
    value: "${CI_REGISTRY}"
  IMG_REPOSITORY:
    description: "Docker image name. Default = project-namespace/project-name"
    value: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
  IMG_TAG:
    description: "Docker image tag. Default = The branch or tag name for which project is built"
    value: "${CI_COMMIT_REF_NAME}"
  IMG_RW_USERNAME:
    description: "Docker image registry username with read/write access. Default = gitlab-ci aka pipeline user"
    value: "${CI_REGISTRY_USER}"
  IMG_RW_PASSWORD:
    description: "Docker image registry password. Default = pipeline token"
    value: "${CI_REGISTRY_PASSWORD}"
  IMG: "${IMG_REGISTRY}/${IMG_REPOSITORY}:${IMG_TAG}"

  ARGO_ENDPOINT:
    description: "ArgoCD server hostname. Default = argocd.pouyan.dev"
    value: "argocd.pouyan.dev"
  ARGO_TOKEN:
    description: "ArgoCD auth token. Default = ARGO_TOKEN_TEH1 secret"
    value: "${ARGO_TOKEN_TEH1}"

  KUBE_NS:
    description: "Kubernetes namespace or OpenShift project to deploy onto. Default = project-namespace"
    value: "${CI_PROJECT_NAMESPACE}"
  KUBE_ENDPOINT:
    description: "Kubernetes cluster api url. Default = https://rancher.pouyan.dev/v3"
    value: "https://rancher.pouyan.dev/v3"
  KUBE_TOKEN:
    description: "Kubernetes cluster api token. Default = KUBE_TOKEN_TEH1 secret"
    value: "${KUBE_TOKEN_TEH1}"

include:
  - local: .gitlab/ci/templates/00-prebuild.gitlab-ci.yml
  - local: .gitlab/ci/templates/01-build.gitlab-ci.yml
  - local: .gitlab/ci/templates/02-release.gitlab-ci.yml
  - local: .gitlab/ci/templates/03-deploy.gitlab-ci.yml
