// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForAddResourceRecord implements pgx.CopyFromSource.
type iteratorForAddResourceRecord struct {
	rows                 []AddResourceRecordParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddResourceRecord) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddResourceRecord) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DomainID,
		r.rows[0].Type,
		r.rows[0].Value,
		r.rows[0].Ttl,
	}, nil
}

func (r iteratorForAddResourceRecord) Err() error {
	return nil
}

func (q *Queries) AddResourceRecord(ctx context.Context, arg []AddResourceRecordParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"resource_records"}, []string{"domain_id", "type", "value", "ttl"}, &iteratorForAddResourceRecord{rows: arg})
}
