// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dnslv.sql

package db

import (
	"context"
)

type AddResourceRecordParams struct {
	DomainID *int32 `json:"domainId"`
	Type     string `json:"type"`
	Value    string `json:"value"`
	Ttl      int32  `json:"ttl"`
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateDomain(ctx context.Context, name string) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainExists = `-- name: DomainExists :one
SELECT id
FROM domains
WHERE name = $1
`

func (q *Queries) DomainExists(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, domainExists, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUnexpiredDomain = `-- name: GetUnexpiredDomain :many

SELECT d.id     AS domain_id,
			 d.name   AS domain_name,
			 rr.id    AS resource_record_id,
			 rr.type  AS resource_record_type,
			 rr.value AS resource_record_value,
			 rr.ttl   AS resource_record_ttl
FROM domains d
			 LEFT JOIN resource_records rr ON d.id = rr.domain_id
WHERE NOW() - (INTERVAL '1 second' * $1::INT) <= d.updated_at
`

type GetUnexpiredDomainRow struct {
	DomainID            int32   `json:"domainId"`
	DomainName          string  `json:"domainName"`
	ResourceRecordID    *int32  `json:"resourceRecordId"`
	ResourceRecordType  *string `json:"resourceRecordType"`
	ResourceRecordValue *string `json:"resourceRecordValue"`
	ResourceRecordTtl   *int32  `json:"resourceRecordTtl"`
}

// DOMAIN AGGREGATE
func (q *Queries) GetUnexpiredDomain(ctx context.Context, ttl int32) ([]GetUnexpiredDomainRow, error) {
	rows, err := q.db.Query(ctx, getUnexpiredDomain, ttl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnexpiredDomainRow
	for rows.Next() {
		var i GetUnexpiredDomainRow
		if err := rows.Scan(
			&i.DomainID,
			&i.DomainName,
			&i.ResourceRecordID,
			&i.ResourceRecordType,
			&i.ResourceRecordValue,
			&i.ResourceRecordTtl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
