// Code generated by go-swagger; DO NOT EDIT.

package dnslv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"gitlab.snapp.ir/pouyanh/lookhub/drivers/api/user/restful/models"
)

// NewDnslvLookupParams creates a new DnslvLookupParams object
//
// There are no default values defined in the spec.
func NewDnslvLookupParams() DnslvLookupParams {

	return DnslvLookupParams{}
}

// DnslvLookupParams contains all the bound params for the dnslv lookup operation
// typically these are obtained from a http.Request
//
// swagger:parameters dnslvLookup
type DnslvLookupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Lookup *models.DnslvLookupCmd
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDnslvLookupParams() beforehand.
func (o *DnslvLookupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.DnslvLookupCmd
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("lookup", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Lookup = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
