// Code generated by go-swagger; DO NOT EDIT.

package dnslv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pouyanh/lookhub/drivers/api/user/restful/models"
)

// DnslvLookupOKCode is the HTTP code returned for type DnslvLookupOK
const DnslvLookupOKCode int = 200

/*
DnslvLookupOK Success

swagger:response dnslvLookupOK
*/
type DnslvLookupOK struct {

	/*
	  In: Body
	*/
	Payload *models.DnslvLookupRsp `json:"body,omitempty"`
}

// NewDnslvLookupOK creates DnslvLookupOK with default headers values
func NewDnslvLookupOK() *DnslvLookupOK {

	return &DnslvLookupOK{}
}

// WithPayload adds the payload to the dnslv lookup o k response
func (o *DnslvLookupOK) WithPayload(payload *models.DnslvLookupRsp) *DnslvLookupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the dnslv lookup o k response
func (o *DnslvLookupOK) SetPayload(payload *models.DnslvLookupRsp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DnslvLookupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DnslvLookupDefault Error

swagger:response dnslvLookupDefault
*/
type DnslvLookupDefault struct {
	_statusCode int
	/*Response locale

	 */
	ContentLanguage string `json:"Content-Language"`

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDnslvLookupDefault creates DnslvLookupDefault with default headers values
func NewDnslvLookupDefault(code int) *DnslvLookupDefault {
	if code <= 0 {
		code = 500
	}

	return &DnslvLookupDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the dnslv lookup default response
func (o *DnslvLookupDefault) WithStatusCode(code int) *DnslvLookupDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the dnslv lookup default response
func (o *DnslvLookupDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithContentLanguage adds the contentLanguage to the dnslv lookup default response
func (o *DnslvLookupDefault) WithContentLanguage(contentLanguage string) *DnslvLookupDefault {
	o.ContentLanguage = contentLanguage
	return o
}

// SetContentLanguage sets the contentLanguage to the dnslv lookup default response
func (o *DnslvLookupDefault) SetContentLanguage(contentLanguage string) {
	o.ContentLanguage = contentLanguage
}

// WithPayload adds the payload to the dnslv lookup default response
func (o *DnslvLookupDefault) WithPayload(payload *models.Error) *DnslvLookupDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the dnslv lookup default response
func (o *DnslvLookupDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DnslvLookupDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Content-Language

	contentLanguage := o.ContentLanguage
	if contentLanguage != "" {
		rw.Header().Set("Content-Language", contentLanguage)
	}

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
