// Code generated by go-swagger; DO NOT EDIT.

package dnslv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DnslvLookupHandlerFunc turns a function with the right signature into a dnslv lookup handler
type DnslvLookupHandlerFunc func(DnslvLookupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DnslvLookupHandlerFunc) Handle(params DnslvLookupParams) middleware.Responder {
	return fn(params)
}

// DnslvLookupHandler interface for that can handle valid dnslv lookup params
type DnslvLookupHandler interface {
	Handle(DnslvLookupParams) middleware.Responder
}

// NewDnslvLookup creates a new http.Handler for the dnslv lookup operation
func NewDnslvLookup(ctx *middleware.Context, handler DnslvLookupHandler) *DnslvLookup {
	return &DnslvLookup{Context: ctx, Handler: handler}
}

/*
	DnslvLookup swagger:route POST /v1/dnslv/lookup dnslv dnslvLookup

Lookup a domain name
*/
type DnslvLookup struct {
	Context *middleware.Context
	Handler DnslvLookupHandler
}

func (o *DnslvLookup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDnslvLookupParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
