mode: privileged

gateways:
  user:
    address: 0.0.0.0:80
    proto: tcp
  metrics:
    address: 0.0.0.0:30089
    proto: tcp

apis:
  user:
    cors.origin: localhost *
    gateways:
      - user
  metrics:
    cors.origin: localhost *
    gateways:
      - metrics

databases:
  dnslv:
    adapter: postgresql
    host: pg.cloud.snp
    port: 5432
    name: lookhub
    username: postgres
    password: postgres
