apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lookhub.fullname" . }}
  namespace: {{ include "lookhub.namespace" . }}
  labels:
    {{- include "lookhub.labels" . | nindent 4 }}
type: Opaque
data: {}
