apiVersion: v1
kind: Service
metadata:
  name: {{ include "lookhub.fullname" . }}
  namespace: {{ include "lookhub.namespace" . }}
  labels:
    {{- include "lookhub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "lookhub.selectorLabels" . | nindent 4 }}
  ports:
    - name: user
      port: 80
      targetPort: 30080
      protocol: TCP
    - name: metrics
      port: 30089
      targetPort: 30089
      protocol: TCP
