// Code generated by go-swagger; DO NOT EDIT.

// Package restapi LookHub - User
//
//	User API
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.1
//	Contact: Pouyan Heyratpour<me@pouyan.dev> https://pouyan.dev
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
