// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "User API",
    "title": "LookHub - User",
    "contact": {
      "name": "Pouyan Heyratpour",
      "url": "https://pouyan.dev",
      "email": "me@pouyan.dev"
    },
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/healthz": {
      "get": {
        "security": [],
        "description": "Health check; Give information about service health, source of build and uptime",
        "tags": [
          "maintenance"
        ],
        "operationId": "healthCheck",
        "responses": {
          "200": {
            "description": "Healthy",
            "schema": {
              "$ref": "#/definitions/ServiceHealth"
            }
          },
          "default": {
            "$ref": "#/responses/Error"
          }
        }
      }
    },
    "/v1/dnslv/lookup": {
      "post": {
        "description": "Lookup a domain name",
        "tags": [
          "dnslv"
        ],
        "operationId": "dnslvLookup",
        "parameters": [
          {
            "$ref": "#/parameters/DnslvLookupCmd"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/DnslvLookupRsp"
            }
          },
          "default": {
            "$ref": "#/responses/Error"
          }
        }
      }
    }
  },
  "definitions": {
    "DnslvLookupCmd": {
      "description": "Lookup command",
      "type": "object",
      "required": [
        "domain"
      ],
      "properties": {
        "domain": {
          "description": "Domain name to lookup",
          "type": "string"
        }
      }
    },
    "DnslvLookupRsp": {
      "description": "Lookup response",
      "type": "object",
      "required": [
        "domain"
      ],
      "properties": {
        "domain": {
          "$ref": "#/definitions/Domain"
        }
      }
    },
    "Domain": {
      "description": "Domain information",
      "type": "object",
      "required": [
        "name",
        "resourceRecords"
      ],
      "properties": {
        "name": {
          "description": "Domain name",
          "type": "string"
        },
        "resourceRecords": {
          "description": "Collection of resource records",
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResourceRecord"
          }
        }
      }
    },
    "Error": {
      "description": "Details of a failure happened during a request",
      "type": "object",
      "properties": {
        "code": {
          "description": "Situation code",
          "type": "string"
        },
        "message": {
          "description": "Descriptive error text",
          "type": "string"
        },
        "traceId": {
          "description": "Request trace id",
          "type": "string"
        }
      }
    },
    "ResourceRecord": {
      "description": "Resource record summary",
      "type": "object",
      "required": [
        "type",
        "value",
        "ttl"
      ],
      "properties": {
        "ttl": {
          "description": "ttl in seconds",
          "type": "integer"
        },
        "type": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "ServiceHealth": {
      "description": "Service health report",
      "type": "object",
      "properties": {
        "buildDate": {
          "description": "reveals date when the executable application was build",
          "type": "string"
        },
        "commit": {
          "description": "git commit hash of the HEAD in the executable application's source code in compile-time",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/ServiceStatus"
        },
        "uptime": {
          "description": "Time since service was started",
          "type": "string"
        },
        "version": {
          "description": "latest git tag or a pseudo-version indicating git tag and commit fingerprint in the executable application's source code in compile-time",
          "type": "string"
        }
      }
    },
    "ServiceStatus": {
      "description": "Service status",
      "type": "string",
      "enum": [
        "Booting",
        "Ready",
        "ShuttingDown"
      ],
      "example": "Ready"
    }
  },
  "parameters": {
    "DnslvLookupCmd": {
      "name": "lookup",
      "in": "body",
      "schema": {
        "$ref": "#/definitions/DnslvLookupCmd"
      }
    }
  },
  "responses": {
    "Error": {
      "description": "Error",
      "schema": {
        "$ref": "#/definitions/Error"
      },
      "headers": {
        "Content-Language": {
          "type": "string",
          "description": "Response locale"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Monitoring, Health Checks, Ping-Pongs, ...",
      "name": "maintenance"
    },
    {
      "description": "Domain name lookup \u0026 resolve",
      "name": "dnslv"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "User API",
    "title": "LookHub - User",
    "contact": {
      "name": "Pouyan Heyratpour",
      "url": "https://pouyan.dev",
      "email": "me@pouyan.dev"
    },
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/healthz": {
      "get": {
        "security": [],
        "description": "Health check; Give information about service health, source of build and uptime",
        "tags": [
          "maintenance"
        ],
        "operationId": "healthCheck",
        "responses": {
          "200": {
            "description": "Healthy",
            "schema": {
              "$ref": "#/definitions/ServiceHealth"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            },
            "headers": {
              "Content-Language": {
                "type": "string",
                "description": "Response locale"
              }
            }
          }
        }
      }
    },
    "/v1/dnslv/lookup": {
      "post": {
        "description": "Lookup a domain name",
        "tags": [
          "dnslv"
        ],
        "operationId": "dnslvLookup",
        "parameters": [
          {
            "name": "lookup",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/DnslvLookupCmd"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/DnslvLookupRsp"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            },
            "headers": {
              "Content-Language": {
                "type": "string",
                "description": "Response locale"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "DnslvLookupCmd": {
      "description": "Lookup command",
      "type": "object",
      "required": [
        "domain"
      ],
      "properties": {
        "domain": {
          "description": "Domain name to lookup",
          "type": "string"
        }
      }
    },
    "DnslvLookupRsp": {
      "description": "Lookup response",
      "type": "object",
      "required": [
        "domain"
      ],
      "properties": {
        "domain": {
          "$ref": "#/definitions/Domain"
        }
      }
    },
    "Domain": {
      "description": "Domain information",
      "type": "object",
      "required": [
        "name",
        "resourceRecords"
      ],
      "properties": {
        "name": {
          "description": "Domain name",
          "type": "string"
        },
        "resourceRecords": {
          "description": "Collection of resource records",
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResourceRecord"
          }
        }
      }
    },
    "Error": {
      "description": "Details of a failure happened during a request",
      "type": "object",
      "properties": {
        "code": {
          "description": "Situation code",
          "type": "string"
        },
        "message": {
          "description": "Descriptive error text",
          "type": "string"
        },
        "traceId": {
          "description": "Request trace id",
          "type": "string"
        }
      }
    },
    "ResourceRecord": {
      "description": "Resource record summary",
      "type": "object",
      "required": [
        "type",
        "value",
        "ttl"
      ],
      "properties": {
        "ttl": {
          "description": "ttl in seconds",
          "type": "integer"
        },
        "type": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "ServiceHealth": {
      "description": "Service health report",
      "type": "object",
      "properties": {
        "buildDate": {
          "description": "reveals date when the executable application was build",
          "type": "string"
        },
        "commit": {
          "description": "git commit hash of the HEAD in the executable application's source code in compile-time",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/ServiceStatus"
        },
        "uptime": {
          "description": "Time since service was started",
          "type": "string"
        },
        "version": {
          "description": "latest git tag or a pseudo-version indicating git tag and commit fingerprint in the executable application's source code in compile-time",
          "type": "string"
        }
      }
    },
    "ServiceStatus": {
      "description": "Service status",
      "type": "string",
      "enum": [
        "Booting",
        "Ready",
        "ShuttingDown"
      ],
      "example": "Ready"
    }
  },
  "parameters": {
    "DnslvLookupCmd": {
      "name": "lookup",
      "in": "body",
      "schema": {
        "$ref": "#/definitions/DnslvLookupCmd"
      }
    }
  },
  "responses": {
    "Error": {
      "description": "Error",
      "schema": {
        "$ref": "#/definitions/Error"
      },
      "headers": {
        "Content-Language": {
          "type": "string",
          "description": "Response locale"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Monitoring, Health Checks, Ping-Pongs, ...",
      "name": "maintenance"
    },
    {
      "description": "Domain name lookup \u0026 resolve",
      "name": "dnslv"
    }
  ]
}`))
}
